### ISSUE TITLE
EPIC: Classic Support

### ISSUE THREAD

**Issue by seanpeters86** [simulationcraft/simc#5821]
Placeholder ticket meant to encompass the work required to get support for Classic Vanilla and/or TBC support into SimC. There are probably lots of things missing from this, but this is a good starting point for anyone interested. See the [contribution file](https://github.com/simulationcraft/simc/blob/shadowlands/CONTRIBUTING.md) for more information on how to [participate](https://github.com/simulationcraft/simc/wiki/Participate).

# Base Module Work
The bulk of the work for any SimC expansion is mostly down to implementing each class spell in the class module and then subsequent [APL](https://github.com/simulationcraft/simc/wiki/ActionLists) work. In order for this work to even start a few prerequisites would be required.
- [x] Branch created for the version of the game, i.e. `classic` or `tbc`
- [ ] Parsing game data into workable Spell Data (somewhat blocked until blizzard publishes client for TBC). Alternatively you could hard code this like it used to be done. [Mage examples can be found here](https://github.com/simulationcraft/simc/blob/43e486ad4c398174c46b43533bc57f650d16b45f/sc_mage.cpp). [Original TBC simc commit here](https://github.com/simulationcraft/simc/commit/23c46dc14df8af784652a12f66da7026a68be3a5).
- [ ] Handling items/character stat integrations. Need to be able to import gear and have it have the correct stats/etc
- [ ] Tier Set Bonus constructs. Need the class modules to be able to implement these
- [ ] Talent tree support, currently this is just a `talents=1231233` system that would need to be adjusted
- [ ] Spell rank support (might be fine? but would need checking, including APL support if needed)
- [ ] Special gear/trinket/enchants/consumables support - [examples from shadowlands](https://github.com/simulationcraft/simc/blob/shadowlands/engine/player/unique_gear_shadowlands.cpp)

# [SimC Client Addon](https://github.com/simulationcraft/simc-addon)
Depends on the base module being done, but the [SimC Addon](https://www.curseforge.com/wow/addons/simulationcraft) would also need updated/supported for Classic.
- [ ] Addon loads gear in game via `/simc` properly

# Class Modules
Each class module will need various work to make it usable for simming. Typically there is one or more devs per spec, but that isn't a hard requirement. Each class will need spell, tier set bonuses, APLs, and talent implementations.
- [ ] Druid - N/A
- [ ] Hunter - N/A
- [ ] Mage - N/A
- [ ] Paladin - N/A
- [ ] Priest - @seanpeters86 
- [ ] Rogue - N/A
- [ ] Shaman - N/A
- [ ] Warlock - N/A
- [ ] Warrior - N/A

# Getting old code working
Note that if you want to get the [Original TBC simc commit here](https://github.com/simulationcraft/simc/commit/23c46dc14df8af784652a12f66da7026a68be3a5) working you just need to remove `-mtune=pentium-m` from the Makefile and then run `./simcraft file=profiles/dedmon max_time=300`

**Comment by seanpeters86** [comment]
I made a new branch that just starts from the old tbc commit from a reference standpoint. This is just hard coded spell data with some basic sim support. You could build from this or fork off of the modern `shadowlands` code base. I added basic instructions for how to run that here: https://github.com/simulationcraft/simc/tree/old-tbc

I think it would probably be best to just create a branch off of `shadowlands` and delete everything except base module stuff and work up from there with hard coded data. That work is started here: https://github.com/simulationcraft/simc/tree/tbc

**Comment by Undertoe** [comment]
@seanpeters86  has there been any update to this?  I can start working on some of the class modules over the next few weeks if there has been any work on spell data.  Immediate ones would be Ret paladin / prot paladin.

**Comment by seanpeters86** [comment]
> @seanpeters86  has there been any update to this?  I can start working on some of the class modules over the next few weeks if there has been any work on spell data.  Immediate ones would be Ret paladin / prot paladin.

No there has been no work on spell data. Would be faster to implement spells manually without spell data. On the tbc branch i was still working on removing all that I'm not sure if that was ever finished.

**Comment by seathasky** [comment]
Curious why QElive (https://questionablyepic.com/) has implemented SIMC for TBC healer builds, but cant find a Simc addon for TBC client. Does the SL Simc addon work in TBC?

**Comment by vituscze** [comment]
The official simc addon did not receive any updates for TBC, so most likely no.

**Comment by Voulk** [comment]
I'm very sorry if I've mislead anyone. The TBC version of QE Live uses it's own addon to import gear, that is heavily based on SimC but is separate. You can grab it here: [https://www.curseforge.com/wow/addons/qe-live-gear-importer-bc](https://www.curseforge.com/wow/addons/qe-live-gear-importer-bc)

**Comment by seathasky** [comment]
> I'm very sorry if I've mislead anyone. The TBC version of QE Live uses it's own addon to import gear, that is heavily based on SimC but is separate. You can grab it here: https://www.curseforge.com/wow/addons/qe-live-gear-importer-bc

Ty Voulk! Thats great to know! I had no idea you guys had an importer! That's awesome news! Any chance you can add a link so people know the addon is available? Or is it already there and i missed it haha

**Comment by Voulk** [comment]
> > I'm very sorry if I've mislead anyone. The TBC version of QE Live uses it's own addon to import gear, that is heavily based on SimC but is separate. You can grab it here: https://www.curseforge.com/wow/addons/qe-live-gear-importer-bc
> 
> Ty Voulk! Thats great to know! I had no idea you guys had an importer! That's awesome news! Any chance you can add a link so people know the addon is available? Or is it already there and i missed it haha

I've just pushed a new build live that has a much clearer link to it. It was much too hard to find previously.

**Comment by tugaman** [comment]
is this project on hold, i would love Simc converted to TBC Classic

**Comment by seanpeters86** [comment]
> is this project on hold, i would love Simc converted to TBC Classic

Need more contributors to help out on the project. My free time is spent on 9.1 at the moment so do not have time to dedicate to this effort.

**Comment by tugaman** [comment]
> > is this project on hold, i would love Simc converted to TBC Classic
> 
> Need more contributors to help out on the project. My free time is spent on 9.1 at the moment so do not have time to dedicate to this effort.

i understand, its a pity tho, simc would be a great tool for TBC classic as well.

**Comment by Thaodan** [comment]
> I'm very sorry if I've mislead anyone. The TBC version of QE Live uses it's own addon to import gear, that is heavily based on SimC but is separate. You can grab it here: https://www.curseforge.com/wow/addons/qe-live-gear-importer-bc

Its a semi fork. Your code reads like s/simc/QE/g
