### ISSUE TITLE
Elemental 11.0.5 PTR Implementation

### ISSUE THREAD

**Issue by wfarr** [simulationcraft/simc#9463]
We're starting to add the new Elemental changes for 11.0.5 in guarded behind `ptr=1`.

This is a tracking issue for implementation work we've done so far:

- [x] Flash of Lightning
    - [x] No longer grants cooldown reduction at all #9459
- [x] Liquid Magma Totem
    - [x] Now grants 8 maelstrom #9460 
- [x] Icefury
    - [x] Lightning Bolt and Chain Lightning can now proc Icefury #9461 
    - [x] Now cleaves up to 4 additional nearby targets #9519 
- [x] Ascendance
    - [x] No longer scales Lava Burst damage based on crit rating #9462 
    - [x] No longer allows no-cooldown Lava Burst spam #9462 
    - [x] No longer allows casting of Lava Beam (this spell is removed) #9462 
    - [x] Now grants 150% multiplier to Overload damage #9462 
    - [x] Now grants +1 Overload in all situations #9462 
    - [x] Now spreads Flame Shock to up to 6 nearby targets (was refresh Flame Shock on existing targets) #9536
    - [x] Now casts a Lava Burst at each of the above targets at 100% efficiency #9536 
- [x] Deeply Rooted Elements
    - [x] Now procs from spenders (was Lava Burst) #9471 
- [x] Primordial Wave
    - [x] Now generates maelstrom #9520 
    - [x] Now grants a guaranteed Lava Surge #9520
- [x] Storm Elemental
    - [x] Now lasts 20 seconds (may be covered by spell data change already, need to confirm)
    - [x] Now increases haste, rather than cast speed of LB and CL #9530 
- [x] Storm Swell
    - [x] Now grants 9% Mastery for 6 seconds (was generates 30 maelstrom) #9525 
- [x] Echo Chamber
    - [x] Now a 40% multiplicative increase to Overload damage (used to be 10% additive) #9529 

### Probably covered by spell data changes, but needs confirming

- [x] Echo of the Elementals
    - [x] Now lasts 10 seconds
- [x] Fire Elemental
    - [x] Now lasts 20 seconds
- [x] Storm Frenzy
    - [x] Now 30% cast time reduction
- [x] Fusion of Elements
    - [x] ~~Only consumed by harmful/damaging spells now~~ This was already marked harmful only in simc, likely just a tooltip update
- [x] Arc Discharge
    - [x] ~~Now also effects Lightning Bolt~~ Nothing to do, this is already handled by the affecting spells table

### New talents

- [x] Herald of the Storms
   - [x] New talent: Casting Lightning Bolt or Chain Lightning reduces the cooldown of Stormkeeper by 2.0 sec. #9467 
- [x] Charged Conduit
    - [x] New talent: Increases the duration of Lightning Rod by 4 seconds and its damage bonus by 25% (multiplicative) #9522 
- [x] Earth Shatter
    - [x] New talent: Increases Earth Shock and Earthquake damage by 8% (multiplicative) and the stat bonuses granted by Elemental Blast by 25% (multiplicative) #9526 
- [x] Erupting Lava
     - [x] New talent: Increases the duration of Flame Shock by 6 seconds.
     - [x] Lava Burst consumes up to 3 seconds of Flame Shock, instantly dealing that damage (how does this behave if fewer than 3 seconds remain?)
     - [x] Lava Burst overloads benefit from Erupting Lava at 50% effectiveness (does this mean parent LvB eats it once and then we 50% that amp here? does the overload eat its own portion of the DoT?)

### Removed talents

- [x] Flow of Power
    - [x] #9469 
- [x] Skybreaker's Fiery Demise
    - [x] #9470 
- [x] Unrelenting Calamity
    - [x] #9468

**Comment by wfarr** [comment]
Calling this feature complete for now. There may be bugs, but we'll deal with them in post.
